#!/bin/bash
set -e

echo "Starting Resource Updater..."

touch /var/log/cron.log

# 将当前容器环境导出为 cron 可读取的文件
echo "# generated by entrypoint.sh" > /etc/container_env
while IFS='=' read -r name val; do
	printf "export %s=%q\n" "$name" "$val" >> /etc/container_env
done < <(env)

# 在运行时写入 crontab
# 使其能 source /etc/container_env
cat > /etc/crontab <<'CRON'
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
0 * * * * root . /etc/container_env; /app/scripts/run-all.sh >> /var/log/cron.log 2>&1
CRON

# 启动时使用 cron 的环境运行一次
echo "Running initial update using cron environment..."
if [ -f /etc/container_env ]; then
	( . /etc/container_env; /app/scripts/run-all.sh 2>&1 | tee -a /var/log/cron.log ) || echo "Initial update failed; see /var/log/cron.log"
else
	/app/scripts/run-all.sh 2>&1 | tee -a /var/log/cron.log || echo "Initial update failed; see /var/log/cron.log"
fi

echo "Starting cron daemon..."
echo "" > /var/log/cron.log
cron && tail -f /var/log/cron.log
